### ISSUE TITLE
clevo-xsm-wmi requires sudo

### ISSUE THREAD

**Issue by joaobrittoneto** [g-arjones/clevo-xsm-wmi#6]
Step 4 works with sudo for me.
```
4. Usage

Adjusting keyboard settings:

$sudo clevo-xsm-wmi
```

**Comment by g-arjones** [comment]
Did you install it with `sudo make install` ? It should be installed with setuid permissions so `sudo` is not necessary when running the utility.

```
arjones@elementaryOS:~$ ls -l /usr/bin/clevo-xsm-wmi 
-rwsr-xr-x 1 root root 52808 Jun 11 14:28 /usr/bin/clevo-xsm-wmi
arjones@elementaryOS:~$ 
```

Make sure permissions are `-rwsr-xr-x`

**Comment by joaobrittoneto** [comment]
> Did you install it with sudo make install? 

Yep

```
joao@javell:~$ ls -l /usr/bin/clevo-xsm-wmi 
-rwxr-xr-x 1 root root 70176 Jun 20 13:36 /usr/bin/clevo-xsm-wmi
```
How to do change permission to `-rwsr -xr -x`?

**Comment by g-arjones** [comment]
`chmod  -c 4755 /usr/bin/clevo-xsm-wmi`
